kiwix/kiwix-android-custom

gen-std-icon.py

If the country code is unspecified the language icon will not be added

Allow no country code to be set

---

phet/info.json
sample_app/info.json
tunisie/info.json
venezuela/info.json
wikimed/info.json
wikimed_mini/info.json
wikimedar/info.json
wikimedde/info.json
wikimedes/info.json
wikimedfa/info.json
wikimedfr/info.json
wikimedja/info.json
wikimedor/info.json
wikimedpt/info.json
wikimedzh/info.json
wikispecies/info.json
wikivoyage/info.json
wikivoyage_europe/info.json
wikivoyagede/info.json
wpbm/info.json

Remove deprecated json zim_file property

---

.github/workflows/main.yml
copy_json_to_kiwix_android.sh

On tag of this repo with the name of a custom app eg `wikimed` that custom app will be published in draft to the play store. 
Final updates pending merge of https://github.com/kiwix/kiwix-android/pull/1597

Custom App Publishing

---

README.md

Update documentation with new process

---

CONTRIBUTING.md

#54 Update CONTRIBUTING.md with steps to make release without ZIM change

---

.github/workflows/publish.yml

Changed branch to test publication and replace secrets in `publish.yml` file

Changed branch to test publication and replace secrets in publish.yml file

---

dwds/res/mipmap-anydpi-v26/ic_launcher.xml
dwds/res/mipmap-anydpi-v26/ic_launcher_round.xml

Currently, we have drawable resource small errors in the DWDS repo. This PR resolves that.

DWDS Resource fix

---

README.md

Following [this ticket](https://github.com/kiwix/kiwix-android-custom/pull/117), it appears a few options were still not documented properly.

A bit more options explained

---

dwds/info.json

Please release an updated verion. Thanks!

Updates DWDS ZIM to v2023-11-20

---

dwds/info.json

@MohitMaliFtechiz Thanks for implementing the "About app" feature! We are in the process of creating a dedicated landing page for the app on our site. Please update the URL accordingly.

DWDS Custom App: Changes "About URL" to forthcoming landing page

---

dwds/info.json

Updates DWDS Custom App ZIM

---

README.md
phet/info.json
sample_app/info.json
tunisie/info.json
venezuela/info.json
wikimed/info.json
wikimedar/info.json
wikimedde/info.json
wikimedes/info.json
wikimedfa/info.json
wikimedfr/info.json
wikimedja/info.json
wikimedmini/info.json
wikimedor/info.json
wikimedpt/info.json
wikimedzh/info.json
wikispecies/info.json
wikivoyage/info.json
wikivoyagede/info.json
wikivoyageeurope/info.json
wpbm/info.json

See https://github.com/kiwix/kiwix-android/pull/3602
* Updated all JSON files to show the "Support app_name" in navigation except dwds.
* Updated `README.md` file to show this new feature.

Updated the `README.md` file to show the `support_url` feature introduce for custom apps.

---

.github/workflows/publish.yml
README.md
dwds/info.json
phet/info.json
sample_app/info.json
tunisie/info.json
venezuela/info.json
wikimed/info.json
wikimedar/info.json
wikimedde/info.json
wikimedes/info.json
wikimedfa/info.json
wikimedfr/info.json
wikimedja/info.json
wikimedmini/info.json
wikimedor/info.json
wikimedpt/info.json
wikimedzh/info.json
wikispecies/info.json
wikivoyage/info.json
wikivoyagede/info.json
wikivoyageeurope/info.json
wpbm/info.json

* Introduced the `upload_bundle` feature in the `info.json` file.
*  When it is set to true, it will upload the bundle to the Play Store. Otherwise, it will upload the APK.
* To adapt this feature we have modified our CI.
* For this change we have modified all the `info.json` files.
* To show this new feature we have updated our README file.
More reference https://github.com/kiwix/kiwix-android/pull/3633

Upload APK to the Play Store for older apps.

---

venezuela/res/mipmap-anydpi-v26/ic_launcher.xml
venezuela/res/mipmap-anydpi-v26/ic_launcher_round.xml

Update Res link of venezula fixed

---

dwds/info.json

Updates DWDS Custom App ZIM to v2024-03-11

---

wikimed/info.json

Please merge, release in beta and if testing is OK, release straight in prod

WikiMed 2024-03

---

wikivoyage/info.json
wikivoyagede/info.json
wikivoyageeurope/info.json

* Using the wikivoyage zim file of `2024-06`.
* Using wikivoyagede zim file of `2024-06`.
* Using wikivoyageeurope zim file of `2024-06`.

Updated the Wikivoyage app's ZIM file URLs to the latest version.

---

dwds/info.json

Updates DWDS Custom App ZIM to v2024-08-24

---

.github/workflows/cd.yml

* Refactored our CD to get the secrets correctly
* Changed the `upload-artifact` version to 4 since it was giving an error.

Improved our cd to get the playStore json file from secrets.

---

phet/info.json

Updated the phet ZIM file to the `2025-03` version.

---

dwds/info.json

Update DWDS Custom App ZIM to v2025-04-08

---

wikimedja/info.json

Fixes https://github.com/kiwix/kiwix-android-custom/issues/161

wikimedja 2025-07 metadata

---

tunisie/info.json

Fixes https://github.com/kiwix/kiwix-android-custom/issues/199

Update info.json for tunisie_2025-07

---

wikimedor/info.json

Fixes https://github.com/kiwix/kiwix-android-custom/issues/214

Update info.json for wikimedor_2025-07

---

README.md

See https://github.com/kiwix/kiwix-android/issues/4389, and https://github.com/kiwix/kiwix-android/pull/4432.

Updated `README` to show correct behavior of `disable_sidebar` key.
